### ISSUE TITLE
Multiple OpenVPN modules won't compile on FreeBSD

### ISSUE THREAD

**Issue by oar-cosmith** [thesparklabs/openvpn-two-factor-extensions#3]
Attempting to hand-compile the extensions on FreeBSD for use with OpenVPN fails with the following compilation error. 

If this is just unsupported, let me know: 
`cc -DPREFIX='"/usr/share/openvpn/pam-u2f"' -DUSE_PAM_DLOPEN=1 "-I." -fPIC -c auth-pam-u2f.c utils.c pamdl.c pamdl.h
auth-pam-u2f.c:758:90: warning: implicit declaration of function 'dlerror' is invalid in C99 [-Wimplicit-function-declaration]
        fprintf(stderr, "AUTH-PAM: BACKGROUND: could not load PAM lib %s: %d\n", pam_so, dlerror());
                                                                                         ^
auth-pam-u2f.c:941:28: warning: incompatible pointer types assigning to 'char *' from 'char (*)[4096]' [-Wincompatible-pointer-types]
            *client_reason = &buffer;
                           ^ ~~~~~~~
2 warnings generated.
pamdl.c:101:1: error: conflicting types for 'pam_strerror'
pam_strerror(pam_handle_t *pamh, int errnum)
^
/usr/include/security/pam_appl.h:142:1: note: previous declaration is here
pam_strerror(const pam_handle_t *_pamh,
^
1 error generated.
gmake: *** [Makefile:10: auth-pam-u2f.o] Error 1
clmbs-ovpn1.eng:/usr/local/src/openvpn-two-factor-extensions/yubikey-u2f-pam-plugin# make
cc  -O2 -pipe -DPREFIX='"/usr/share/openvpn/pam-u2f"' -DUSE_PAM_DLOPEN=1 -c pamdl.c -o pamdl.o
pamdl.c:101:1: error: conflicting types for 'pam_strerror'
pam_strerror(pam_handle_t *pamh, int errnum)
^
/usr/include/security/pam_appl.h:142:1: note: previous declaration is here
pam_strerror(const pam_handle_t *_pamh,
^
1 error generated.
*** Error code 1

Stop.
`

**Comment by trametheka** [comment]
~~It looks like you (or FreeBSD) are using a new or older version of the pam library source where the pam_strerror definition is actually in the header. Try removing pamdl.h from the makefile (line 10) and compiling again.~~

Strike that, try removing the pam_strerror definition from pamdl.c (line 100). If you get more errors like this, instead you might want to try compiling with -DUSE_PAM_DLOPEN=0 instead.

**Comment by oar-cosmith** [comment]
Unfortunately, this didn't solve the issue. While the code now compiles, the OpenVPN server can't initialize the new module: 
```
Tue Jul  7 13:31:25 2020 PLUGIN_INIT: could not load plugin shared object /usr/share/openvpn/pam-u2f/auth-pam-u2f.so: /usr/share/openvpn/pam-u2f/auth-pam-u2f.so: Undefined symbol "pam_strerror"
Tue Jul  7 13:31:25 2020 Exiting due to fatal error
Tue Jul  7 13:45:44 2020 PLUGIN_INIT: could not load plugin shared object /usr/share/openvpn/pam-fido2/auth-pam-fido2.so: /usr/share/openvpn/pam-fido2/auth-pam-fido2.so: Undefined symbol "pam_strerror"
Tue Jul  7 13:45:44 2020 Exiting due to fatal error
```

Note, this is even if 'make'ing with: ```-DUSE_PAM_DLOPEN=0```

Again, if this is unsupported, let me know. But if we can get this working I'll make sure to toss it up on the FreeBSD Forums so others can use it. 

I really appreciate you looking into this with me.

**Comment by trametheka** [comment]
Per the readme in the project folder, you also need a patched version of OpenVPN for these plugins to work, there is no way to do U2F on vanilla OpenVPN via a plugin. You can find the latest patch in our PPA by downloading the tar.xz, we only have pre-compiled versions for Ubuntu - https://launchpad.net/~sparklabs/+archive/ubuntu/ppa/+packages

We only support Ubuntu officially, I'll try and find some time to look into FreeBSD, the issue is certainly the PAM headers available within the operating system, with a bit of trial and error with the compilation flags it should be workable. Please ensure you have a libpam-dev package installed or equivilent for FreeBSD

**Comment by trametheka** [comment]
@oar-cosmith spent a bit of time having a look at this. For whatever reason, the plugin is refusing to link to the system pam library. I'm afraid my experience is just too limited with freebsd to really dig into why. Hopefully someone with more experience with freebsd can take a look into it in the future.
